name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: dependency (apt-get)
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make libc6-dev \
            gcc g++ \
            python3 python3-pip python3-pytest

    - name: dependency (pip)
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: make
      run: |
        make

    - name: make test
      run: |
        make test

    - name: make clean
      run: |
        make clean